// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64 && linux && ebpf

package capture

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type pgshadowSslSslArgs struct {
	_      structs.HostLayout
	BufPtr uint64
	Fd     uint32
	_      [4]byte
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	pgshadowSslMapSslEvents              = "ssl_events"
	pgshadowSslMapSslReadArgs            = "ssl_read_args"
	pgshadowSslMapSslStats               = "ssl_stats"
	pgshadowSslMapSslWriteArgs           = "ssl_write_args"
	pgshadowSslMapTargetPid              = "target_pid"
	pgshadowSslProgUprobeSslReadEnter    = "uprobe_ssl_read_enter"
	pgshadowSslProgUprobeSslWriteEnter   = "uprobe_ssl_write_enter"
	pgshadowSslProgUretprobeSslReadExit  = "uretprobe_ssl_read_exit"
	pgshadowSslProgUretprobeSslWriteExit = "uretprobe_ssl_write_exit"
)

// loadPgshadowSsl returns the embedded CollectionSpec for pgshadowSsl.
func loadPgshadowSsl() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_PgshadowSslBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load pgshadowSsl: %w", err)
	}

	return spec, err
}

// loadPgshadowSslObjects loads pgshadowSsl and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*pgshadowSslObjects
//	*pgshadowSslPrograms
//	*pgshadowSslMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadPgshadowSslObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadPgshadowSsl()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// pgshadowSslSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type pgshadowSslSpecs struct {
	pgshadowSslProgramSpecs
	pgshadowSslMapSpecs
	pgshadowSslVariableSpecs
}

// pgshadowSslProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type pgshadowSslProgramSpecs struct {
	UprobeSslReadEnter    *ebpf.ProgramSpec `ebpf:"uprobe_ssl_read_enter"`
	UprobeSslWriteEnter   *ebpf.ProgramSpec `ebpf:"uprobe_ssl_write_enter"`
	UretprobeSslReadExit  *ebpf.ProgramSpec `ebpf:"uretprobe_ssl_read_exit"`
	UretprobeSslWriteExit *ebpf.ProgramSpec `ebpf:"uretprobe_ssl_write_exit"`
}

// pgshadowSslMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type pgshadowSslMapSpecs struct {
	SslEvents    *ebpf.MapSpec `ebpf:"ssl_events"`
	SslReadArgs  *ebpf.MapSpec `ebpf:"ssl_read_args"`
	SslStats     *ebpf.MapSpec `ebpf:"ssl_stats"`
	SslWriteArgs *ebpf.MapSpec `ebpf:"ssl_write_args"`
	TargetPid    *ebpf.MapSpec `ebpf:"target_pid"`
}

// pgshadowSslVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type pgshadowSslVariableSpecs struct {
}

// pgshadowSslObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadPgshadowSslObjects or ebpf.CollectionSpec.LoadAndAssign.
type pgshadowSslObjects struct {
	pgshadowSslPrograms
	pgshadowSslMaps
	pgshadowSslVariables
}

func (o *pgshadowSslObjects) Close() error {
	return _PgshadowSslClose(
		&o.pgshadowSslPrograms,
		&o.pgshadowSslMaps,
	)
}

// pgshadowSslMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadPgshadowSslObjects or ebpf.CollectionSpec.LoadAndAssign.
type pgshadowSslMaps struct {
	SslEvents    *ebpf.Map `ebpf:"ssl_events"`
	SslReadArgs  *ebpf.Map `ebpf:"ssl_read_args"`
	SslStats     *ebpf.Map `ebpf:"ssl_stats"`
	SslWriteArgs *ebpf.Map `ebpf:"ssl_write_args"`
	TargetPid    *ebpf.Map `ebpf:"target_pid"`
}

func (m *pgshadowSslMaps) Close() error {
	return _PgshadowSslClose(
		m.SslEvents,
		m.SslReadArgs,
		m.SslStats,
		m.SslWriteArgs,
		m.TargetPid,
	)
}

// pgshadowSslVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadPgshadowSslObjects or ebpf.CollectionSpec.LoadAndAssign.
type pgshadowSslVariables struct {
}

// pgshadowSslPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadPgshadowSslObjects or ebpf.CollectionSpec.LoadAndAssign.
type pgshadowSslPrograms struct {
	UprobeSslReadEnter    *ebpf.Program `ebpf:"uprobe_ssl_read_enter"`
	UprobeSslWriteEnter   *ebpf.Program `ebpf:"uprobe_ssl_write_enter"`
	UretprobeSslReadExit  *ebpf.Program `ebpf:"uretprobe_ssl_read_exit"`
	UretprobeSslWriteExit *ebpf.Program `ebpf:"uretprobe_ssl_write_exit"`
}

func (p *pgshadowSslPrograms) Close() error {
	return _PgshadowSslClose(
		p.UprobeSslReadEnter,
		p.UprobeSslWriteEnter,
		p.UretprobeSslReadExit,
		p.UretprobeSslWriteExit,
	)
}

func _PgshadowSslClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed pgshadowssl_arm64_bpfel.o
var _PgshadowSslBytes []byte
