// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64 && linux && ebpf

package capture

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	pgshadowXdpMapCfgPort      = "cfg_port"
	pgshadowXdpMapPktRing      = "pkt_ring"
	pgshadowXdpMapStats        = "stats"
	pgshadowXdpProgPgshadowXdp = "pgshadow_xdp"
)

// loadPgshadowXdp returns the embedded CollectionSpec for pgshadowXdp.
func loadPgshadowXdp() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_PgshadowXdpBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load pgshadowXdp: %w", err)
	}

	return spec, err
}

// loadPgshadowXdpObjects loads pgshadowXdp and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*pgshadowXdpObjects
//	*pgshadowXdpPrograms
//	*pgshadowXdpMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadPgshadowXdpObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadPgshadowXdp()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// pgshadowXdpSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type pgshadowXdpSpecs struct {
	pgshadowXdpProgramSpecs
	pgshadowXdpMapSpecs
	pgshadowXdpVariableSpecs
}

// pgshadowXdpProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type pgshadowXdpProgramSpecs struct {
	PgshadowXdp *ebpf.ProgramSpec `ebpf:"pgshadow_xdp"`
}

// pgshadowXdpMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type pgshadowXdpMapSpecs struct {
	CfgPort *ebpf.MapSpec `ebpf:"cfg_port"`
	PktRing *ebpf.MapSpec `ebpf:"pkt_ring"`
	Stats   *ebpf.MapSpec `ebpf:"stats"`
}

// pgshadowXdpVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type pgshadowXdpVariableSpecs struct {
}

// pgshadowXdpObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadPgshadowXdpObjects or ebpf.CollectionSpec.LoadAndAssign.
type pgshadowXdpObjects struct {
	pgshadowXdpPrograms
	pgshadowXdpMaps
	pgshadowXdpVariables
}

func (o *pgshadowXdpObjects) Close() error {
	return _PgshadowXdpClose(
		&o.pgshadowXdpPrograms,
		&o.pgshadowXdpMaps,
	)
}

// pgshadowXdpMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadPgshadowXdpObjects or ebpf.CollectionSpec.LoadAndAssign.
type pgshadowXdpMaps struct {
	CfgPort *ebpf.Map `ebpf:"cfg_port"`
	PktRing *ebpf.Map `ebpf:"pkt_ring"`
	Stats   *ebpf.Map `ebpf:"stats"`
}

func (m *pgshadowXdpMaps) Close() error {
	return _PgshadowXdpClose(
		m.CfgPort,
		m.PktRing,
		m.Stats,
	)
}

// pgshadowXdpVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadPgshadowXdpObjects or ebpf.CollectionSpec.LoadAndAssign.
type pgshadowXdpVariables struct {
}

// pgshadowXdpPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadPgshadowXdpObjects or ebpf.CollectionSpec.LoadAndAssign.
type pgshadowXdpPrograms struct {
	PgshadowXdp *ebpf.Program `ebpf:"pgshadow_xdp"`
}

func (p *pgshadowXdpPrograms) Close() error {
	return _PgshadowXdpClose(
		p.PgshadowXdp,
	)
}

func _PgshadowXdpClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed pgshadowxdp_arm64_bpfel.o
var _PgshadowXdpBytes []byte
